const twilio = require('twilio');
const AccessToken = twilio.jwt.AccessToken;
const { VideoGrant } = AccessToken;

const generateToken = config => { // Generates an access token (AccessToken object) to authenticate the user to Twilio's servers
  return new AccessToken(
    config.twilio.accountSid,
    config.twilio.apiKey,
    config.twilio.apiSecret,
    options = { identity: 'user' }
  );
};

const videoToken = (identity, room, config) => { // Generates a Twillio Access Token to authenticate a user joining a room
  let videoGrant;
  if (typeof room !== 'undefined') { // If the room already exists, join it. User is granted access to the room
    videoGrant = new VideoGrant({ room });
  } else {
    videoGrant = new VideoGrant(); // If the room does not exist, create a new one with a new name generated by Twilio servers
  }
  const token = generateToken(config); 
  token.addGrant(videoGrant); // Grants the user access to the video room
  token.identity = identity; // Identifies the user to the Twilio servers
  return token;
};

module.exports = { videoToken };